version: '3.5'

services:            
    glassfish:
        build: images/glassfish
        ports:
            - "8080:8080"
            - "4848:4848"
        links:
            - postgres:db
    postgres:
        build: images/postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=amtprojet1
            - POSTGRES_PASSWORD=pswrd
            - POSTGRES_DB=GestionDesCours
            - PGDATA=/var/lib/postgresql/data/pgdata            
        volumes:
             - ../images/postgres/data/ :/var/lib/postgres/data
        