version: '2'

services:
    widfly:
        build: ../images/widfly
        ports:
            - "9090:8080"
            - "9990:9990"
          
    postgres:
        build: ./images/postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=amtprojet1
            - POSTGRES_PASSWORD=pswrd
            - POSTGRES_DB=GestionDesCours
            - PGDATA=/var/lib/postgresql/data/pgdata
            
        volumes:
            - ./images/postgres/data/ :/var/lib/postgres/data
        